[package]
name = "supplement-proc-macro"
version = "0.1.2"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Proc macro for supplement. Not indetended to be used directly."

[lib]
proc-macro = true

[dependencies]
syn = "2"
quote = "1"
proc-macro2 = "1"
