[package]
name = "supplement-tests"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
supplement = { path = ".." }
env_logger = '*'
log = '*'

[build-dependencies]
supplement = { path = ".." }
clap = { version = "4", features = ["derive"] }
